title: Recetas Naranjas
url: "https://recetas.sofanaranja.com" # need to change this when we use our own site
github_repo:  https://github.com/bomberstudios/recetas

# Build settings
# highlighter: pygments # this is deprecated in 3.0
# markdown: redcarpet # this is deprecated too
kramdown:
  extensions: ['smart', 'no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'with_toc_data']
sass:
  style: compressed

# Dynamic Content
collections:
  recetas:
    output: true
    permalink: /receta/:path/
  ingredientes:
    output: true
    permalink: /ingrediente/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "recetas"
    values:
      layout: "receta"
